# Generated by Django 4.1.5 on 2023-02-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
