# Generated by Django 4.1.5 on 2023-02-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_post_image_name_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
